function out = formatColumnName(in)
    % mapping rules
    key_value_pairs = { ...
        'ProjectName',          'Project Name';...
        'ImageName',            'Image Name';...
        'RegionID',             'Region ID';...
        'PixelSize',            'Pixel Size';...
        'RegionCenter',         'Region Center (x, y)';...
        'RegionWidth_px',       'Region Width (px)';...
        'RegionHeight_px',      'Region Height (px)';...
        'RegionWidth_phys',     'Region Width';...
        'RegionHeight_phys',    'Region Height';...
        'ROICenter',            'ROI Center (x, y)';...
        'ROIWidth_px',          'ROI Width (px)';...
        'ROIHeight_px',         'ROI Height (px)';...
        'ROIWidth_phys',        'ROI Width';...
        'ROIHeight_phys',       'ROI Height';...
        'ROIRotationAngle',     'ROI Rotation Angle (°)';...
        'PeakDistance_px',      'Peak Distance (px)';...
        'PeakWidth1_px',        'Peak Width 1 (px)';...
        'PeakWidth2_px',        'Peak Width 2 (px)';...
        'PeakDistance_phys',    'Peak Distance';...
        'PeakWidth1_phys',      'Peak Width 1';...
        'PeakWidth2_phys',      'Peak Width 2';...
        };

    map = containers.Map(key_value_pairs(:,1),key_value_pairs(:,2));

    if isKey(map, in)
        out = map(in);
    else
        % input used as output
        out = in;
    end
end