function peaksData = analyzeROIHeightProfile(I,ROI,config,theta)
%ANALYZEROIHEIGHTPROFILE Run the rectangular linescan and peak analysis.

linescanData = desmostorm.analysis.profile.measure2D(I, ...
    ROI.CenterX, ...
    ROI.CenterY, ...
    ROI.Width, ...
    ROI.Height, ...
    theta, ...
    'Interp','linear');

peaksData = desmostorm.analysis.image.autofit.makePeaksData( ...
    linescanData.HeightProfile, ...
    linescanData.HeightDist, ...
    config);
end
