function peaksData = analyzeROIWidthProfile(I,ROI,config)
%ANALYZEROIWIDTHPROFILE Run peak analysis on the rectified width profile.

linescanData = desmostorm.analysis.profile.measure2D(I, ...
    ROI.CenterX, ...
    ROI.CenterY, ...
    ROI.Width, ...
    ROI.Height, ...
    ROI.RotationAngle, ...
    'Interp','linear');

peaksData = desmostorm.analysis.image.autofit.makePeaksData( ...
    linescanData.WidthProfile(:), ...
    linescanData.WidthDist(:), ...
    config);
end
