function peaksData = makePeaksData(signal,location,config)
%MAKEPEAKSDATA Construct PeaksData with autofit-safe smoothing flags.
%
% Peak detection uses the app's configured measurement thresholds, while the
% later boundary search applies its own extra smoothing so ROI geometry fitting
% can be hardened independently from final peak measurement settings.

smoothPeaks = config.PeakSmoothing > 0;
peakSmoothing = max(1,config.PeakSmoothing);

peaksData = desmostorm.analysis.PeaksData( ...
    signal, ...
    location, ...
    "MinPeakDistance",config.MinPeakDistance, ...
    "MinPeakHeight",config.MinPeakHeight, ...
    "PeakSmoothing",peakSmoothing, ...
    "Smooth",smoothPeaks, ...
    "MinPeakHeightMode",'absolute', ...
    "MinPeakProminenceMode",'absolute');
end
